/// Fishing regions for filtering species.
const List<String> fishingRegions = [
  '🌍 All Regions',
  '🌎 North America',
  '🌍 Europe & UK',
  '🌊 Mediterranean',
  '🌎 South America',
  '🌍 Africa',
  '🌏 Asia',
  '🌏 Australia & Pacific',
  '🌴 Caribbean',
];

/// Sub-regions for North America.
const List<String> northAmericaSubRegions = [
  'Canada',
  'United States',
];

/// Fish species grouped by region.
/// Each species can appear in multiple regions.
const Map<String, List<String>> fishByRegion = {
  '🌍 All Regions': [
    'Amberjack',
    'Barracuda',
    'Bluefish',
    'Cod',
    'Flounder',
    'Grouper',
    'Mackerel',
    'Mahimahi (Dorado)',
    'Marlin',
    'Sailfish',
    'Salmon (Atlantic)',
    'Swordfish',
    'Tarpon',
    'Tuna (Albacore)',
    'Tuna (Bluefin)',
    'Tuna (Skipjack)',
    'Tuna (Yellowfin)',
    'Yellowtail',
  ],
  'United States': [
    'Bass (Largemouth)',
    'Bass (Smallmouth)',
    'Bass (Striped)',
    'Bass (Sea)',
    'Bluegill',
    'Bowfin',
    'Bream',
    'Carp (Common)',
    'Catfish (Channel)',
    'Catfish (Flathead)',
    'Crappie (Black)',
    'Crappie (White)',
    'Freshwater Drum (Sheepshead)',
    'Gar (Alligator)',
    'Gar (Longnose)',
    'Muskellunge (Muskie)',
    'Perch (Yellow)',
    'Pickerel (Chain)',
    'Pike (Northern)',
    'Pumpkinseed',
    'Rock Bass',
    'Sauger',
    'Sunfish (Green)',
    'Walleye',
    'Warmouth',
    'Brook Trout (Speckled)',
    'Brown Trout',
    'Bull Trout',
    'Cutthroat Trout',
    'Kokanee Salmon',
    'Lake Trout',
    'Rainbow Trout (Steelhead)',
    'Splake',
    'Lake Whitefish',
    'Mountain Whitefish',
    'Round Whitefish',
    'Lake Sturgeon',
    'White Sturgeon',
    'American Eel',
    'Goldeye',
    'Mooneye',
    'Burbot (Ling Cod)',
    // ── Atlantic & Gulf Coast ─────────────────────────────────────────────────
    'Amberjack',
    'Atlantic Cod',
    'Atlantic Mackerel',
    'Atlantic Salmon',
    'Atlantic Wolffish',
    'Barracuda',
    'Black Drum',
    'Bluefish',
    'Bluefin Tuna',
    'Cobia',
    'Croaker (Atlantic)',
    'Dolphin (Mahi-Mahi)',
    'Flounder (Southern)',
    'Flounder (Summer)',
    'Flounder (Winter)',
    'Gag Grouper',
    'Grouper (Black)',
    'Grouper (Goliath)',
    'Grouper (Red)',
    'Haddock',
    'Halibut (Atlantic)',
    'Herring (Atlantic)',
    'Hogfish',
    'Jack Crevalle',
    'King Mackerel (Kingfish)',
    'Ladyfish',
    'Marlin (Blue)',
    'Marlin (White)',
    'Monkfish',
    'Mutton Snapper',
    'Ocean Perch (Redfish)',
    'Pollock',
    'Pompano (Florida)',
    'Red Grouper',
    'Red Snapper',
    'Redfish (Red Drum)',
    'Sailfish',
    'Scup (Porgy)',
    'Shad (American)',
    'Sheepshead',
    'Smelt (Rainbow)',
    'Snapper (Cubera)',
    'Snapper (Yellowtail)',
    'Snook',
    'Spanish Mackerel',
    'Spotted Seatrout',
    'Striped Bass',
    'Swordfish',
    'Tapefish',
    'Tarpon',
    'Triggerfish (Gray)',
    'Tripletail',
    'Tuna (Albacore)',
    'Tuna (Bigeye)',
    'Tuna (Skipjack)',
    'Tuna (Yellowfin)',
    'Weakfish',
    'Whiting (Kingfish)',
    'Yellowtail Amberjack',
    // ── Pacific Coast ─────────────────────────────────────────────────────────
    'Albacore Tuna',
    'Barred Surfperch',
    'Cabezon',
    'California Halibut',
    'California Yellowtail',
    'Chinook Salmon (King)',
    'Chum Salmon (Dog)',
    'Coho Salmon (Silver)',
    'Eulachon (Candlefish)',
    'Greenling (Kelp)',
    'Herring (Pacific)',
    'Lingcod',
    'Pacific Cod',
    'Pacific Halibut',
    'Pacific Mackerel',
    'Pink Salmon (Humpy)',
    'Rockfish (Black)',
    'Rockfish (Bocaccio)',
    'Rockfish (Canary)',
    'Rockfish (Vermilion)',
    'Rockfish (Yelloweye)',
    'Sablefish (Black Cod)',
    'Salmon Shark',
    'Sockeye Salmon (Red)',
    'Spiny Dogfish',
    'Sturgeon (White)',
    'Surf Smelt',
  ],
  'Canada': [
    // ── Freshwater Game Fish ─────────────────────────────────────────────────
    'Bass (Largemouth)',
    'Bass (Smallmouth)',
    'Bluegill',
    'Bowfin',
    'Burbot (Ling Cod)',
    'Carp (Common)',
    'Catfish (Channel)',
    'Crappie (Black)',
    'Freshwater Drum (Sheepshead)',
    'Gar (Longnose)',
    'Muskellunge (Muskie)',
    'Perch (Yellow)',
    'Pike (Northern)',
    'Pumpkinseed',
    'Rock Bass',
    'Sauger',
    'Sunfish',
    'Walleye (Pickerel)',

    // ── Trout, Char & Salmon (Freshwater) ─────────────────────────────────────
    'Arctic Char',
    'Arctic Grayling',
    'Brook Trout (Speckled)',
    'Brown Trout',
    'Cutthroat Trout',
    'Dolly Varden (Bull Trout)',
    'Kokanee Salmon',
    'Lake Trout',
    'Rainbow Trout (Steelhead)',
    'Splake',
    'Tiger Trout',

    // ── Whitefish & Cisco ─────────────────────────────────────────────────────
    'Cisco (Lake Herring)',
    'Inconnu (Sheefish)',
    'Lake Whitefish',
    'Mountain Whitefish',
    'Round Whitefish',

    // ── Suckers, Minnows & Rough Fish ─────────────────────────────────────────
    'Goldeye',
    'Mooneye',
    'White Sucker',

    // ── Sturgeon ──────────────────────────────────────────────────────────────
    'Lake Sturgeon',
    'Shortnose Sturgeon',
    'White Sturgeon',

    // ── Atlantic Canada Saltwater ─────────────────────────────────────────────
    'American Eel',
    'Atlantic Cod',
    'Atlantic Mackerel',
    'Atlantic Salmon',
    'Atlantic Wolffish',
    'Bluefin Tuna',
    'Capelin',
    'Flounder (Winter)',
    'Flounder (Yellowtail)',
    'Gaspereau (Alewife)',
    'Haddock',
    'Halibut (Atlantic)',
    'Herring (Atlantic)',
    'Monkfish (Anglerfish)',
    'Ocean Perch (Redfish)',
    'Pollock',
    'Shad (American)',
    'Smelt (Rainbow)',
    'Striped Bass',
    'Swordfish',
    'Tomcod (Frostfish)',
    'White Hake',

    // ── Pacific Canada Saltwater ──────────────────────────────────────────────
    'Chinook Salmon (King)',
    'Chum Salmon (Dog)',
    'Coho Salmon (Silver)',
    'Eulachon (Candlefish)',
    'Herring (Pacific)',
    'Lingcod',
    'Pacific Cod',
    'Pacific Halibut',
    'Pink Salmon (Humpy)',
    'Rockfish (Canary)',
    'Rockfish (Quillback)',
    'Rockfish (Yelloweye)',
    'Sablefish (Black Cod)',
    'Salmon Shark',
    'Sockeye Salmon (Red)',
    'Spiny Dogfish',
    'Surf Smelt',
    'White Sturgeon',
  ],
  '🌍 Europe & UK': [
    'Bream',
    'Carp',
    'Cod',
    'Flounder',
    'Haddock',
    'Halibut',
    'Herring',
    'Mackerel',
    'Perch (Yellow)',
    'Pike (Northern)',
    'Pollock',
    'Rainbow Trout',
    'Salmon (Atlantic)',
    'Sole',
    'Tuna (Bluefin)',
    'Whitefish',
  ],
  '🌊 Mediterranean': [
    'Amberjack',
    'Barracuda',
    'Bream',
    'Grouper',
    'Jack Crevalle',
    'Mackerel',
    'Mahimahi (Dorado)',
    'Salmon (Atlantic)',
    'Snapper (Red)',
    'Swordfish',
    'Tuna (Bluefin)',
    'Tuna (Skipjack)',
    'Tuna (Yellowfin)',
    'Yellowtail',
  ],
  '🌎 South America': [
    'Bass (Sea)',
    'Bream',
    'Carp',
    'Catfish (Channel)',
    'Catfish (Flathead)',
    'Grouper',
    'Mackerel',
    'Mahimahi (Dorado)',
    'Rainbow Trout',
    'Snapper (Red)',
    'Snook',
    'Tarpon',
    'Tilapia',
  ],
  '🌍 Africa': [
    'Amberjack',
    'Barracuda',
    'Bream',
    'Carp',
    'Catfish (Channel)',
    'Grouper',
    'Kingfish',
    'Mackerel',
    'Mahimahi (Dorado)',
    'Marlin',
    'Sailfish',
    'Sole',
    'Swordfish',
    'Tilapia',
    'Tuna (Yellowfin)',
  ],
  '🌏 Asia': [
    'Amberjack',
    'Bream',
    'Carp',
    'Catfish (Channel)',
    'Grouper',
    'Jack Crevalle',
    'Mackerel',
    'Mahimahi (Dorado)',
    'Marlin',
    'Rainbow Trout',
    'Salmon (Chinook)',
    'Salmon (Coho)',
    'Sardine',
    'Snapper (Red)',
    'Snapper (Yellowtail)',
    'Sole',
    'Swordfish',
    'Tilapia',
    'Tuna (Bluefin)',
    'Tuna (Skipjack)',
    'Tuna (Yellowfin)',
    'Yellowtail',
  ],
  '🌏 Australia & Pacific': [
    'Amberjack',
    'Barracuda',
    'Bream',
    'Flathead',
    'Flounder',
    'Grouper',
    'Jack Crevalle',
    'Kingfish',
    'Mackerel',
    'Mahimahi (Dorado)',
    'Marlin',
    'Rainbow Trout',
    'Salmon (Atlantic)',
    'Snapper (Red)',
    'Snapper (Yellowtail)',
    'Snook',
    'Sole',
    'Swordfish',
    'Tarpon',
    'Tuna (Albacore)',
    'Tuna (Bluefin)',
    'Tuna (Skipjack)',
    'Tuna (Yellowfin)',
    'Yellowtail',
  ],
  '🌴 Caribbean': [
    'Amberjack',
    'Barracuda',
    'Bluefish',
    'Grouper',
    'Jack Crevalle',
    'Kingfish',
    'Mackerel',
    'Mahimahi (Dorado)',
    'Marlin',
    'Pompano',
    'Sailfish',
    'Snapper (Red)',
    'Snapper (Yellowtail)',
    'Snook',
    'Swordfish',
    'Tarpon',
    'Tuna (Skipjack)',
    'Tuna (Yellowfin)',
    'Yellowtail',
  ],
};

/// Get the list of species for a given region.
/// Falls back to all species if region not found.
List<String> speciesForRegion(String region) {
  final species = fishByRegion[region];
  if (species != null) return species;
  if (fishingRegions.contains(region) || region == '🌎 North America') {
    return fishByRegion['🌍 All Regions']!;
  }
  return fishByRegion['🌍 All Regions']!;
}

/// A flat, deduplicated list of ALL species across all regions.
/// Use this for voice recognition and global searches.
List<String> get allFishSpecies {
  final seen = <String>{};
  final result = <String>[];
  for (final list in fishByRegion.values) {
    for (final s in list) {
      if (seen.add(s.toLowerCase())) {
        result.add(s);
      }
    }
  }
  return result;
}
